-- vim.opt_local.shiftwidth = 4 -- 자동 들여쓰기 시 사용되는 공백 수
-- vim.opt_local.tabstop = 4 -- 탭 문자가 차지하는 공백 수
-- vim.opt_local.softtabstop = 4 -- 편집 시 탭을 몇 개의 공백으로 취급할지 설정
-- vim.opt_local.expandtab = true
--
-- local config = {
--   cmd = { vim.fn.stdpath("data") .. "/mason/bin/jdtls" },
--   root_dir = vim.fs.dirname(vim.fs.find({ "gradlew", ".git", "mvnw" }, { upward = true })[1]),
-- }
-- require("jdtls").start_or_attach(config)
