return {
  -- {
  --   "rose-pine/neovim",
  --   name = "rose-pine",
  --   config = function()
  --     require("rose-pine").setup({
  --       variant = "moon",
  --       dark_variant = "moon",
  --       disable_italics = true,
  --       styles = {
  --         bold = true,
  --         italic = true,
  --         transparency = true,
  --       },
  --       highlight_groups = {
  --         TelescopeBorder = { fg = "highlight_high", bg = "none" },
  --         TelescopeNormal = { bg = "none" },
  --         TelescopePromptNormal = { bg = "base" },
  --         TelescopeResultsNormal = { fg = "subtle", bg = "none" },
  --         TelescopeSelection = { fg = "text", bg = "base" },
  --         TelescopeSelectionCaret = { fg = "rose", bg = "rose" },
  --       },
  --     })
  --   end,
  -- },
  -- {
  --   "LazyVim/LazyVim",
  --   opts = {
  --     colorscheme = "rose-pine",
  --   },
  -- },
}
