
# Live config reload (changes require restart)
live_config_reload = true

# Theme
# import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]
import = ["~/.config/alacritty/themes/themes/rose-pine.toml"]

[env]
term = "xterm-256color"

[font]
size = 20.0

[font.normal]
family = "D2codingligature Nerd font mono"
style = "Regular"

[font.italic]
family = "D2codingligature Nerd font mono"
style = "Italic"

[font.bold]
family = "D2codingligature Nerd font mono"
style = "Bold"

[font.bold_italic]
family = "D2codingligature Nerd font mono"
style = "Italic"


# Offset is the extra space around each character. `offset.y` can be thought of
# as modifying the line spacing, and `offset.x` as modifying the letter spacing
# I've given in 14 spacing which fits really well with my fonts, you may change it
# to your convenience but make sure to adjust 'glyph_offset' appropriately post that
[font.offset]
x = 0
y = 0

# Note: This requires RESTART
# By default when you change the offset above you'll see an issue, where the texts are bottom
# aligned with the cursor, this is to make sure they center align.
# This offset should usually be 1/2 of the above offset-y being set.
[font.glyph_offset]
x = 0
# Keeping this as half of offset to vertically align the text in cursor
y = 0


[keyboard]
bindings = [
  # { key = "Up", mods = "Alt", chars = "\u001b[1;5a" },
  # { key = "Return", mods = "Command", action = "ToggleFullscreen" },
  { key = "Left", mods = "Alt", chars = "\u001bb" },
  { key = "Right", mods = "Alt", chars = "\u001bf" },
  { key = "V", mods = "Command", action = "Paste" },
  { key = "C", mods = "Command", action = "Copy" },
  { key = "Z", mods = "Command", chars = "^Z" },
  { key = "Back", mods = "Command", chars = "\u0015" },   # Delete line
  { key = "Back", mods = "Alt", chars = "\u001b\u007f" }, # Delete word
]

[selection]
# When set to `true`, selected text will be copied to the primary clipboard.
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

# ctrl-^ doesn't work in some terminals like alacritty
[shell]
program = "/opt/homebrew/bin/fish"

[window]
dynamic_padding = true
dynamic_title = true
startup_mode = "Windowed"
option_as_alt = "Both"
decorations = "full"

[window.padding]
x = 2
y = 2
